#!/usr/bin/env python
"""One-command database bring-up and app wiring.

    python scripts/setup_database.py

Does everything between an empty Neon project and two mobile apps that can
talk to it:

    1. verify DATABASE_URL reaches a Postgres with pgvector
    2. apply migrations
    3. seed the deterministic synthetic corpus
    4. derive graph edges and node metrics
    5. provision one device key per app
    6. write those keys into the mobile .env files (gitignored)
    7. smoke-test the full search -> decision -> audit loop

Safe to re-run: migrations are idempotent, seeding refuses to duplicate, and
device keys are only created when the label does not already exist.
"""

from __future__ import annotations

import argparse
import asyncio
import secrets
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.config import get_settings
from app.db import apply_migrations, create_pool
from app.dependencies import hash_device_key

REPO = Path(__file__).resolve().parent.parent.parent
FIELD_ENV = REPO / "mobile" / "apps" / "field" / ".env"
ENROLL_ENV = REPO / "mobile" / "apps" / "enroll" / ".env"

DEVICES = [
    ("FIELD-DEV-01", "field", FIELD_ENV),
    ("ENROLL-DEV-01", "enroll", ENROLL_ENV),
]


async def run_script(name: str, *args: str) -> subprocess.CompletedProcess[str]:
    """Run a sibling script off the event loop.

    These are separate processes because each one is independently runnable
    and already tested; re-implementing them inline would duplicate logic
    that has to stay identical.
    """
    return await asyncio.to_thread(
        subprocess.run,
        [sys.executable, str(Path(__file__).parent / name), *args],
        cwd=Path(__file__).parent.parent,
        capture_output=True,
        text=True,
    )


def step(n: int, text: str) -> None:
    print(f"\n[{n}/7] {text}")


async def provision_device(conn, label: str, app: str, pepper: str) -> str | None:
    """Create a device key, or return None when the label already exists.

    Only the hash is stored, so an existing key cannot be recovered — it can
    only be replaced. Returning None keeps re-runs from silently invalidating
    a key already installed on a handset.
    """
    existing = await conn.fetchval("SELECT device_id FROM device WHERE label = $1", label)
    if existing:
        return None

    raw = secrets.token_urlsafe(32)
    await conn.execute(
        "INSERT INTO device (key_hash, label, app) VALUES ($1, $2, $3)",
        hash_device_key(raw, pepper),
        label,
        app,
    )
    return raw


def write_env(path: Path, api_url: str, device_key: str | None) -> None:
    """Write a mobile .env, preserving an existing key when we made no new one."""
    path.parent.mkdir(parents=True, exist_ok=True)

    existing_key = ""
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("EXPO_PUBLIC_DEVICE_KEY="):
                existing_key = line.split("=", 1)[1].strip()

    key = device_key or existing_key
    path.write_text(
        "# Generated by backend/scripts/setup_database.py. Gitignored.\n"
        "# The device key is a coarse gate, not authentication: it identifies a\n"
        "# handset and makes revocation possible. It proves nothing about who\n"
        "# is holding the device.\n"
        f"EXPO_PUBLIC_API_URL={api_url}\n"
        f"EXPO_PUBLIC_DEVICE_KEY={key}\n"
        "EXPO_PUBLIC_USE_ONNX=false\n",
        encoding="utf-8",
    )


async def run(api_url: str, skip_seed: bool) -> int:
    settings = get_settings()

    if not settings.database_url:
        print(
            "DATABASE_URL is not set.\n\n"
            "  1. Create a free Postgres at https://neon.tech (pgvector is built in)\n"
            "  2. Copy backend/.env.example to backend/.env\n"
            "  3. Put the POOLED connection string in DATABASE_URL\n"
            "     (the host contains '-pooler'; Neon's direct connection limit is tight)\n"
            "  4. Set DEVICE_KEY_PEPPER to any long random string\n"
            "  5. Re-run this script\n",
            file=sys.stderr,
        )
        return 2

    if not settings.device_key_pepper:
        print("DEVICE_KEY_PEPPER is not set in backend/.env", file=sys.stderr)
        return 2

    if settings.dataset_mode != "synthetic":
        print("refusing to run: DATASET_MODE is not 'synthetic'", file=sys.stderr)
        return 2

    step(1, "Connecting and checking for pgvector")
    pool = await create_pool(settings)
    try:
        async with pool.acquire() as conn:
            version = await conn.fetchval("SELECT version()")
            print(f"      {version.split(',')[0]}")
            await conn.execute("CREATE EXTENSION IF NOT EXISTS vector")
            await conn.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
            ext = await conn.fetchval("SELECT extversion FROM pg_extension WHERE extname='vector'")
            print(f"      pgvector {ext}")

        step(2, "Applying migrations")
        applied = await apply_migrations(pool)
        print(
            f"      {len(applied) or 'no'} migration(s) applied"
            if applied
            else "      already up to date"
        )

        step(3, "Seeding synthetic data")
        if skip_seed:
            print("      skipped (--skip-seed)")
        else:
            result = await run_script("seed_synthetic.py")
            print("      " + "\n      ".join(result.stdout.strip().splitlines()[-8:]))
            if result.returncode != 0:
                print(result.stderr, file=sys.stderr)
                return 3

        step(4, "Deriving graph edges and node metrics")
        result = await run_script("compute_edges.py", "--with-metrics")
        print("      " + "\n      ".join(result.stdout.strip().splitlines()[-3:]))

        step(5, "Provisioning device keys")
        created: dict[str, str | None] = {}
        async with pool.acquire() as conn:
            for label, app_kind, _ in DEVICES:
                raw = await provision_device(conn, label, app_kind, settings.device_key_pepper)
                created[label] = raw
                print(f"      {label:<16} {'created' if raw else 'already exists, kept'}")

        step(6, "Writing mobile .env files")
        for label, _app_kind, path in DEVICES:
            write_env(path, api_url, created[label])
            print(f"      {path.relative_to(REPO)}")

        step(7, "Smoke-testing the search loop")
        async with pool.acquire() as conn:
            counts = await conn.fetchrow(
                """
                SELECT (SELECT count(*) FROM person)         AS persons,
                       (SELECT count(*) FROM face_embedding) AS embeddings,
                       (SELECT count(*) FROM edge)           AS edges,
                       (SELECT count(*) FROM case_record)    AS cases
                """
            )
            print(
                f"      {counts['persons']} persons · {counts['embeddings']} embeddings · "
                f"{counts['cases']} cases · {counts['edges']} edges"
            )

            # Prove the vector path actually returns something rankable.
            probe = await conn.fetchval(
                "SELECT embedding::text FROM face_embedding WHERE model_id = $1 LIMIT 1",
                settings.model_ids[0],
            )
            top = await conn.fetchval(
                """
                SELECT 1 - MIN(embedding <=> $1::text::vector(512))
                FROM   face_embedding WHERE model_id = $2
                """,
                probe,
                settings.model_ids[0],
            )
            print(f"      nearest-neighbour self-similarity: {float(top):.4f} (expect 1.0000)")
    finally:
        await pool.close()

    print("\n" + "=" * 68)
    print("  DATABASE READY")
    print("=" * 68)
    for label, _app_kind, _path in DEVICES:
        raw = created.get(label)
        if raw:
            print(f"  {label}  X-Perigee-Device-Key: {raw}")
    print(f"\n  Both apps point at: {api_url}")
    print("\n  Start the API:   cd backend && uvicorn app.main:app --reload")
    print("  Run Field:       cd mobile/apps/field  && corepack pnpm exec expo start --dev-client")
    print("  Run Enroll:      cd mobile/apps/enroll && corepack pnpm exec expo start --dev-client")
    print("\n  Device keys are shown ONCE. Only their hash is stored.")
    print("=" * 68)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Bring up the Perigee database and wire the apps")
    parser.add_argument(
        "--api-url",
        default="http://10.0.2.2:8000",
        help="Base URL the apps should call. 10.0.2.2 is the Android emulator's "
        "alias for the host; use your LAN IP for a physical device.",
    )
    parser.add_argument("--skip-seed", action="store_true")
    args = parser.parse_args()
    return asyncio.run(run(args.api_url, args.skip_seed))


if __name__ == "__main__":
    raise SystemExit(main())
