export const requiredRouteFiles = [
  'app/_layout.tsx',
  'app/index.tsx',
  'app/shift.tsx',
  'app/(tabs)/_layout.tsx',
  'app/(tabs)/home.tsx',
  'app/(tabs)/pending.tsx',
  'app/(tabs)/scan.tsx',
  'app/(tabs)/activity.tsx',
  'app/(tabs)/more.tsx',
  'app/scan/capture.tsx',
  'app/scan/review.tsx',
  'app/scan/fixture.tsx',
  'app/scan/searching.tsx',
  'app/results/[searchId].tsx',
  'app/person/[id].tsx',
  'app/graph/[id].tsx',
  'app/settings/diagnostics.tsx',
  'app/settings/camera.tsx',
  'app/settings/connection.tsx',
  'app/settings/accessibility.tsx',
  'app/settings/about.tsx',
] as const;
