// @ts-nocheck -- the production config plugin is CommonJS because Expo loads it with Node.
import { createRequire } from 'node:module';
import { describe, expect, it } from 'vitest';

const require = createRequire(import.meta.url);
const {
  injectAbiSplits,
  injectVisionCameraFeatureFlag,
  upsertGradleProperty,
} = require('./withAndroidReleaseOptimizations');

describe('injectAbiSplits', () => {
  const buildGradle = `android {
    namespace 'com.perigee.testcamera'

    packagingOptions {
        jniLibs {
            useLegacyPackaging = false
        }
    }
}`;

  it('adds Pixel phone and emulator ABI outputs without a universal APK', () => {
    const result = injectAbiSplits(buildGradle);

    expect(result).toContain('// @generated by perigee-camera-lab: abi-splits');
    expect(result).toContain('enable true');
    expect(result).toContain('universalApk false');
    expect(result).toContain('include "arm64-v8a", "x86_64"');
    expect(result).not.toContain('armeabi-v7a');
    expect(result).not.toMatch(/include .*\bx86\b(?!_64)/);
    expect(result.indexOf('splits {')).toBeLessThan(result.indexOf('packagingOptions {'));
  });

  it('is idempotent across repeated prebuilds', () => {
    const once = injectAbiSplits(buildGradle);
    expect(injectAbiSplits(once)).toBe(once);
  });

  it('fails loudly if Expo changes the generated Gradle structure', () => {
    expect(() => injectAbiSplits('android { namespace "test" }')).toThrow(
      /packagingOptions anchor/,
    );
  });
});

describe('injectVisionCameraFeatureFlag', () => {
  const mainApplication = `package com.perigee.testcamera

import com.facebook.react.ReactNativeApplicationEntryPoint.loadReactNative

class MainApplication {
  override fun onCreate() {
    super.onCreate()
    loadReactNative(this)
    ApplicationLifecycleDispatcher.onApplicationCreate(this)
  }
}`;

  it('enables RawProps JSI before Expo creates the React runtime', () => {
    const result = injectVisionCameraFeatureFlag(mainApplication);

    expect(result).toContain('ReactNativeFeatureFlags.dangerouslyReset()');
    expect(result).toContain('override fun useRawPropsJsiValue(): Boolean = true');
    expect(result.indexOf('useRawPropsJsiValue')).toBeLessThan(
      result.indexOf('ApplicationLifecycleDispatcher.onApplicationCreate'),
    );
  });

  it('is idempotent across repeated prebuilds', () => {
    const once = injectVisionCameraFeatureFlag(mainApplication);
    expect(injectVisionCameraFeatureFlag(once)).toBe(once);
  });

  it('fails loudly if the generated entry point changes', () => {
    expect(() => injectVisionCameraFeatureFlag('class MainApplication')).toThrow(
      /loadReactNative anchor/,
    );
  });
});

describe('upsertGradleProperty', () => {
  it('replaces an existing Expo image-codec property instead of duplicating it', () => {
    const properties = [
      { type: 'comment', value: 'Image support' },
      { type: 'property', key: 'expo.gif.enabled', value: 'true' },
    ];

    upsertGradleProperty(properties, 'expo.gif.enabled', 'false');

    expect(properties).toEqual([
      { type: 'comment', value: 'Image support' },
      { type: 'property', key: 'expo.gif.enabled', value: 'false' },
    ]);
  });

  it('adds a missing property exactly once', () => {
    const properties = [];
    upsertGradleProperty(properties, 'expo.webp.enabled', 'false');
    upsertGradleProperty(properties, 'expo.webp.enabled', 'false');

    expect(properties).toEqual([
      { type: 'property', key: 'expo.webp.enabled', value: 'false' },
    ]);
  });
});
