const {
  withAppBuildGradle,
  withGradleProperties,
  withMainApplication,
} = require('@expo/config-plugins');

const MARKER = '// @generated by perigee-camera-lab: abi-splits';
const ANCHOR = '    packagingOptions {';
const CAMERA_FLAG_MARKER =
  '// @generated by perigee-camera-lab: vision-camera-raw-props';
const CAMERA_IMPORT_ANCHOR =
  'import com.facebook.react.ReactNativeApplicationEntryPoint.loadReactNative';
const CAMERA_LOAD_ANCHOR = '    loadReactNative(this)';

const ABI_SPLITS = `    ${MARKER}
    splits {
        abi {
            reset()
            enable true
            universalApk false
            include "arm64-v8a", "x86_64"
        }
    }

`;

function injectAbiSplits(contents) {
  if (contents.includes(MARKER)) return contents;
  if (!contents.includes(ANCHOR)) {
    throw new Error(
      'Could not find the packagingOptions anchor in android/app/build.gradle.',
    );
  }

  return contents.replace(ANCHOR, `${ABI_SPLITS}${ANCHOR}`);
}

function upsertGradleProperty(properties, key, value) {
  const current = properties.find(
    (property) => property.type === 'property' && property.key === key,
  );
  if (current) {
    current.value = value;
    return;
  }

  properties.push({ type: 'property', key, value });
}

function injectVisionCameraFeatureFlag(contents) {
  if (contents.includes(CAMERA_FLAG_MARKER)) return contents;
  if (
    !contents.includes(CAMERA_IMPORT_ANCHOR) ||
    !contents.includes(CAMERA_LOAD_ANCHOR)
  ) {
    throw new Error(
      'Could not find the loadReactNative anchor in MainApplication.kt.',
    );
  }

  const imports = `${CAMERA_IMPORT_ANCHOR}
import com.facebook.react.internal.featureflags.ReactNativeFeatureFlags
import com.facebook.react.internal.featureflags.ReactNativeNewArchitectureFeatureFlagsDefaults`;
  const enableFlag = `${CAMERA_LOAD_ANCHOR}
    ${CAMERA_FLAG_MARKER}
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // RN 0.81 defaults this off, while VisionCamera 5 passes JSI-backed preview props.
      // loadReactNative has loaded native libraries but has not created the React runtime yet.
      ReactNativeFeatureFlags.dangerouslyReset()
      ReactNativeFeatureFlags.override(
        object : ReactNativeNewArchitectureFeatureFlagsDefaults(true) {
          override fun useFabricInterop(): Boolean = true
          override fun useShadowNodeStateOnClone(): Boolean = true
          override fun useRawPropsJsiValue(): Boolean = true
        }
      )
    }`;

  return contents
    .replace(CAMERA_IMPORT_ANCHOR, imports)
    .replace(CAMERA_LOAD_ANCHOR, enableFlag);
}

function withAndroidReleaseOptimizations(config) {
  const withSplits = withAppBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== 'groovy') {
      throw new Error('Perigee ABI splits currently require a Groovy app build.gradle.');
    }

    gradleConfig.modResults.contents = injectAbiSplits(
      gradleConfig.modResults.contents,
    );
    return gradleConfig;
  });

  const withCameraFlag = withMainApplication(withSplits, (mainConfig) => {
    if (mainConfig.modResults.language !== 'kt') {
      throw new Error('Perigee VisionCamera setup requires MainApplication.kt.');
    }
    mainConfig.modResults.contents = injectVisionCameraFeatureFlag(
      mainConfig.modResults.contents,
    );
    return mainConfig;
  });

  return withGradleProperties(withCameraFlag, (gradleConfig) => {
    // Pixel 7 hardware is arm64; Android Studio's Pixel 7 AVD is x86_64.
    upsertGradleProperty(
      gradleConfig.modResults,
      'reactNativeArchitectures',
      'arm64-v8a,x86_64',
    );
    // This JPEG-only test app does not need Expo's optional GIF/WebP decoders.
    upsertGradleProperty(gradleConfig.modResults, 'expo.gif.enabled', 'false');
    upsertGradleProperty(gradleConfig.modResults, 'expo.webp.enabled', 'false');
    upsertGradleProperty(
      gradleConfig.modResults,
      'expo.webp.animated',
      'false',
    );
    return gradleConfig;
  });
}

module.exports = withAndroidReleaseOptimizations;
module.exports.injectAbiSplits = injectAbiSplits;
module.exports.injectVisionCameraFeatureFlag = injectVisionCameraFeatureFlag;
module.exports.upsertGradleProperty = upsertGradleProperty;
